name: Build & Release (Debug)

on:
  push:
    branches:
      - builds
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant Permission
        run: chmod +x gradlew

      - name: Build Stable Debug
        run: ./gradlew assembleStableDebug

      - name: Rename APK
        run: |
          mv app/build/outputs/apk/stable/debug/*.apk MiraiExt-debug.apk

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: MiraiExt Debug Build
          files: MiraiExt-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}